version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - akurganow
  versioning-strategy: increase-if-necessary
